spring:
  datasource:
    url: jdbc:h2:mem:customertstdb
    username: root
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true

info:
  app:
    name: customer-service
    description: spring boot application
    version: 1.0.0
